name: Metrics

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:      # Manual trigger

permissions:
  contents: write         # allow the action to commit back to the repo

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg

          # GitHub Tokens
          token:           ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Base sections
          base: header, activity, community, repositories

          # Plugins
          plugin_achievements:        yes
          plugin_achievements_display: compact
          plugin_achievements_limit:   5

          plugin_activity:       yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all

          plugin_languages: yes
          plugin_lines:     yes
          plugin_followup:  yes
          plugin_repositories: yes

          # Display settings
          config_timezone: America/Vancouver
          config_twemoji:  yes
          config_octicon:  yes
