name: GitHub Metrics

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:      # Manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Create Assets Directory
        run: mkdir -p assets
          
      - name: Download Border Separator 
        run: |
          curl -o assets/borderseparator.gif "https://raw.githubusercontent.com/trinib/trinib/a5f2e3208fe96799e32a82f1d2ff3535dfa29124/assets/borderseparator.gif"
          
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          
          # Core metrics
          base: header, activity, community, repositories
          config_display: large
          config_timezone: America/Vancouver
          config_animations: yes
          config_twemoji: yes
          config_octicon: yes
          
          # Extended stats
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Coding habits
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_days: 30
          plugin_habits_trim: yes
          
          # Activity & contributions  
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          
          # Starred topics
          plugin_stars: yes
          plugin_stars_limit: 5
          
          # Discussions
          plugin_discussions: yes
          
          # Lines of code
          plugin_lines: yes
          
          # Followup
          plugin_followup: yes
          plugin_followup_indepth: yes
          
          # Notable contributions
          plugin_notable: yes
          
          # Activity overview
          plugin_traffic: yes
          
          # Commit calendar
          plugin_calendar: yes
          plugin_calendar_limit: 1
