name: Metrics

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:      # Manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg

          # GitHub Tokens
          token: ${{ secrets.METRICS_TOKEN }}            # For reading
          committer_token: ${{ secrets.METRICS_TOKEN }}  # For writing to repo

          # Base sections
          base: header, activity, community, repositories

          # Plugins
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_languages: yes
          plugin_lines: yes
          plugin_followup: yes        # Spiderweb (radar) graph
          plugin_repositories: yes
          plugin_ratings: yes         # Contribution scorecard
          plugin_ratings_animations: yes
          plugin_ratings_theme: neon 

          # Display settings
          config_timezone: America/Vancouver
          config_twemoji: yes         # GitHub emoji support
          config_octicon: yes         # GitHub icons (stars, PRs, etc.)
