name: Metrics

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"    # every day at midnight UTC
  workflow_dispatch:      # manual trigger

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    # ← only run the real work on the schedule event
    if: github.event_name == 'schedule'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    # so empty commits still count

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@main
        with:
          filename: metrics.svg
          token:           ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories
          plugin_achievements:        yes
          plugin_achievements_display: compact
          plugin_achievements_limit:   5
          plugin_activity:       yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_languages: yes
          plugin_lines:     yes
          plugin_followup:  yes
          plugin_repositories: yes
          config_timezone: America/Vancouver
          config_twemoji:  yes
          config_octicon:  yes

      - name: Commit & push metrics.svg
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add metrics.svg
          git commit --allow-empty -m "chore: daily metrics update"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
