name: GitHub Metrics

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:      # Manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Create Assets Directory
        run: mkdir -p assets
          
      - name: Download Border Separator 
        run: |
          curl -o assets/borderseparator.gif "https://raw.githubusercontent.com/trinib/trinib/a5f2e3208fe96799e32a82f1d2ff3535dfa29124/assets/borderseparator.gif"
          
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          
          # Activity overview
          plugin_traffic: yes
          
          # Commit calendar
          plugin_calendar: yes
